### PR TITLE
Fix cert audit excess output

### PR DESCRIPTION
**Pull request by iLoveTux**
Fixes [this issue](https://github.com/McIndi/mast/issues/16)

@mharden108 @steveyeof @briankearney 
please review as quickly as possible as this is to remedy an issue for a support customer.

### CODE REVIEW

**Comment by iLoveTux** [comment]
As this is urgent, I am merging. You can still add code review after this is merged, please do.

**Comment by steveyeof** [comment]
Urgent definitely. When you can spare some time, could we talk about the code logic that snagged us here? This is an edge case that probably needs to be kept in mind in designing the test suite. The question seems to be how to stub out in our sand box conditions that should not occur in properly managed environments.

**Comment by iLoveTux** [comment]
Would you like to talk over the phone, or here in the pull request?

**Comment by steveyeof** [comment]
Let's do it here so we don't have to take notes and can retrace the thought process. I missed the note that this came up from a support customer, I was thinking this involved the "other client where things are not as they should be", but it's still an edge case to be considered.

**Comment by steveyeof** [comment]
Refreshed the browser, it must take too long to compose my thoughts, I think I'm caught up now. Nothing too serious after all, thanks

**Pull request merged**
