### PR TITLE
Fs sync ignore errors

### PR DESCRIPTION
**Pull request by iLoveTux**
Opening this pull request to peer review.

@briankearney @jimb400 @mharden108 @steveyeof 

Please review changes to code and respond. If no objections I will merge this pull request End Of Business today.

### CODE REVIEW

**Comment by briankearney** [comment]
I am still getting errors that cause the script to error out...

`D:\tools\mast\2.1.0>mast.bat usrbin\fs-sync.py from_dp -a HOSTNAME -c CREDS -n -l store:/// --out-dir tmp\ExportedForSyncComparisonDiff\HOSTNAME\default\store -D default -r -i`

`HOSTNAME`
`        default`
 `               store:/// -> tmp\ExportedForSyncComparisonDiff\HOSTNAME\default\store\HOSTNAME`
`                        ERROR downloading above directory stacktrace can be found in the logs`

`D:\tools\mast\2.1.0>type var\log\mast.datapower.fs_sync.log`

See the attached file...
[addToER.txt](https://github.com/McIndi/mast.installer/files/188766/addToER.txt)

**Comment by iLoveTux** [comment]
See the comment [here](https://github.com/McIndi/mast/issues/2#issuecomment-200954649) in the original issue. The problem is that we are handling the bulk-download at a lower level than this script, `DataPower.copy_directory()` to be specific. I was able to implement most of the `--ignore-errors` functionality in the script itself, so I let this go for the time being thinking I was covering your use case.

I was not aware that a more granular approach to `from_dp` was vital to your use case. I will put this higher up on my list of priorities.

**Comment by iLoveTux** [comment]
Added new issue [here](https://github.com/McIndi/mast/issues/3) to remedy this situation with `fs-sync from_dp`

**Comment by iLoveTux** [comment]
I believe that the [latest commit](https://github.com/McIndi/mast.installer/commit/b313255b21027a8dd296400f29326dbda77031aa) the issue about [atomic downloads](https://github.com/McIndi/mast/issues/3).

[link to the updated file](https://raw.githubusercontent.com/McIndi/mast.installer/fs-sync-ignore-errors/mast/installer/files/contrib/fs-sync.py) (Right-Click -> Save As)

@briankearney @jimb400 @mharden108 @steveyeof 

Please add code-reviews and peer-reviews along with questions and comments below.

**Comment by briankearney** [comment]
Unfortunately, I am still getting errors that cause the latest commit script to error out...

Details are in the attached file.

[addToER.txt](https://github.com/McIndi/mast.installer/files/189626/addToER.txt)

**Comment by iLoveTux** [comment]
I saw something similar, it shouldn't error out, but similarly while doing store: it failed on the last file, maybe that's happening to you. Try on the cert: location it should fail multiple times.

**Comment by iLoveTux** [comment]
Nevermind, I found the problem...I forgot to propagate `ignore_errors` through the recursive calls. Fixing now. will update soon.

**Comment by iLoveTux** [comment]
I think I have it fixed.
[here's a link to the file](https://raw.githubusercontent.com/McIndi/mast.installer/fs-sync-ignore-errors/mast/installer/files/contrib/fs-sync.py) (Right-Click -> Save As)

**Pull request merged**
